#!/bin/bash
##ENVIRONMENT SETTINGS; CHANGE WITH CAUTION
#SBATCH --export=NONE                #Do not propagate environment
#SBATCH --get-user-env=L             #Replicate login environment
#
##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=llava-1.6       #Set the job name to "JobExample2"
#SBATCH --time=6:30:00               #Set the wall clock limit to 6hr and 30min
#SBATCH --nodes=1                    #Request 1 node
#SBATCH --ntasks-per-node=1          #Request 8 tasks/cores per node
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G                     #Request 8GB per node
#SBATCH --gres=gpu:a100:1 
#SBATCH --output=stdout.%x.%j
#SBATCH --error=stderr.%x.%j 
#
##OPTIONAL JOB SPECIFICATIONS
##SBATCH --mail-type=ALL              #Send email on all job events
##SBATCH --mail-user=pavan_santosh@tamu.edu    #Send all emails to email_address 
#
##First Executable Line
#
module load GCCcore/12.3.0 Python
module load cuDNN
export TRITON_CACHE_DIR=/scratch/user/pavan_santosh/triton_cache
source /scratch/user/pavan_santosh/milebench/MileBench/mileenv/bin/activate
python evaluate.py --data-dir /scratch/user/pavan_santosh/milebench-data/MileBench --dataset MMCoQA --result-dir outputs/llava-v1.6-7b
##

