## LLaVA 7B
llava-v1.6-7b:
    model_name: llava-v1.6-7b
    model_dir: /scratch/user/pavan_santosh/llava-v1.6/llava-v1.6-vicuna-7b-hf
    start_ratio: 0.1    # Keep first 10% tokens
    recent_ratio: 0.1   # Keep recent 10% tokens
    gen_kwargs:
        max_new_tokens: 200
        min_new_tokens: 1
        do_sample: false
        temperature: 0.0
    max_context_len: 4096
    n_tokens_per_image: 256